baseURL = 'https://haz-2520.github.io/Third-Tertile/'
languageCode = 'en-us'
title = 'The Third Tertile'
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  showReadingTime = true

[params.profileMode]
  enabled = true
  title = "Anon"
  subtitle = "Math, AI, Machine Learning, Algorithms, DevOps & Cloud Engineer · Azure · CI/CD · IaC"
  imageUrl = ""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Haz-2520"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/your-profile"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1
